export const SIGNIN = 'SIGNIN'
export const SIGNUP = 'SIGNUP'
export const SIGNOUT = 'SIGNOUT'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
